### ISSUE TITLE
Add checks to ensure consistency of default units

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/Archive-VisionEval#165]
Need to add some checks to ensure that the default units (units.csv in the defs directory). I've come across one problem and can think of two more that need to be addressed.

1. Units are missing for one or more of the complex data types -- I found this error yesterday. Default units are necessary in order for the framework to convert the units of datasets produced from a module to the units used in the datastore. When a default for a type is missing, the convertUnits function saves NA values in the datastore and a warning is issued. The framework should check that default units exist for all complex types recognized by the framework. This can be checked during model initialization by making sure that there are entries in the 'Type' column of the units.csv file for all complex types.

2. Incorrectly specified default units -- The default units need to be checked to ensure that they are consistent with the units recognized for the data type by the framework (i.e. Types function). There will be an error message in this case, but that will happen when the module is run, rather than up front during model initialization. This can be checked during model initialization by making sure that all entries in the 'Units' column of the units.csv are consistent with recognized units for the type.

3. Consistency of default units between referenced datastores -- If a model run uses datastore references (e.g. for scenario management) and the default units defined for the model run are inconsistent with the default units for the referenced datastore, the results of the model run may be wrong and the problem will be difficult to trace unless the user happens to know that the default units need to be consistent between datastores. This can be checked during model initialization by comparing the 'Units' components of the model state files for the model run and the referenced datastore.

4. Consistency of default units between datastores used for module testing -- as with #3, inconsistent definitions of units can cause errors that are difficult to trace. To solve this, some functionality will need to be added for testing to read the default units of the datastore that is copied to the tests directory and check those units with the definitions for the modules being tested. An error should be thrown if there are inconsistencies. We also need to go back and edit the units.csv files in all of the packages to make them all consistent.

**Comment by bstabler** [comment]
Moving issues here - https://github.com/VisionEval/VisionEval-Dev/issues
