### ISSUE TITLE
Modify readDatastoreTables function to return values in same units as saved in

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/Archive-VisionEval#176]
When datasets are set in the datastore, units are converted to the default units of the datastore. This is the intended behavior and works fine during model runs because the framework converts units to whatever is specified in module specifications. However, confusion can be caused when using the readDatastoreTables function to query the datastore and check values or compute performance measures  because the datasets that are returned are in the units stored in the datastore rather than in the units output from the module. So for example, GHG emissions rates are output in grams per mile but are stored in the datastore in kilograms per mile because the default units for mass are kilograms. The attributes of the returned dataset are consistent with how the dataset is stored so there is no confusion there. In the example, the UNITS attribute of the GHG emissions rate dataset is KG/MI so it is consistent with the data that is returned. However, if the user is expecting GM/MI and is not aware that KG/MI is being returned, they will be confused.

The first thing that should be done is to modify readDatastoreTables to return the UNITS attributes for the datasets so that users are adequately informed.

The second thing that should be done is to modify readDatastoreTables to enable a user to specify the UNITS they want for the dataset that is returned.

**Comment by bstabler** [comment]
Moving issues here - https://github.com/VisionEval/VisionEval-Dev/issues
