### ISSUE TITLE
Currency data can't be handled as compound data type

### ISSUE THREAD

**Issue by gregorbj** [gregorbj/Archive-VisionEval#180]
The framework automatically deflates the values of currency data to specified years or the base year. This only works for currency data that is not specified as a compound data type (e.g USD/MI). It is imperative that all currency data be specified as currency type and not as compound type in order to insure that values
are deflated appropriately. This is bound to cause some confusion for module developers, so the framework should be modified to deflate currency values that are in a compound data type. Meanwhile the
developer documentation needs to explain this.

**Comment by bstabler** [comment]
Moving issues here - https://github.com/VisionEval/VisionEval-Dev/issues
