### ISSUE TITLE
Initialize script in packages

### ISSUE THREAD

**Issue by goreaditya** [gregorbj/Archive-VisionEval#183]
I noticed an issue of validating required user inputs by using an *Initialize* script in packages. ***VERPAT*** and ***VERSPM*** do not share many modules, and the respective inputs from the same package. For e.g. *CreateBasePlaceTypes* module in the **VELandUse** package is only used by ***VERPAT***. This module needs input that requires validation. This can be done using the *Initialize* script but this poses a problem when running ***VERSPM*** as this input is not required by the ***RSPM*** model. Maybe some of these standard validation methods (like checking proportions by year or checking NAs) can be moved to the visioneval framework. *Initialize* script is great for optional inputs but creates a problem when the user inputs are necessary.

**Comment by gregorbj** [comment]
Yes that is a problem. I don't see an obvious solution in the framework itself for checking several data fields simultaneously. Here is a different idea. Perhaps we can add an optional specification that would be like the 'Call' specification. This 'Initialize' specification could be used to identify the name of an initialization module. When the 'initializeModel' function compiles the list of specifications for all the modules, it would identify any modules identified in their 'Initialize' specifications and would add those modules to the specifications list. This approach would be similar to the current but would allow multiple  initialization scripts.

**Comment by goreaditya** [comment]
Adding an 'initialize.R' script in `https://github.com/gregorbj/VisionEval/tree/master/sources/modules/VELandUse/R` to validate data in *bzone_pop_emp_prop.csv* (used in **CreateBasePlaceTypes** and module) creates a problem as this file is needed by ***VERPAT*** but not by ***VERSPM***. Running ***VERSPM*** model will fail in this scenario.

**Comment by bstabler** [comment]
See https://github.com/gregorbj/VisionEval/wiki/Project-Meeting-2018.06.21

**Comment by bstabler** [comment]
Moving issues here - https://github.com/VisionEval/VisionEval-Dev/issues
