### ISSUE TITLE
Table format error in documentation

### ISSUE THREAD

**Issue by mrspeel** [gregorbj/Archive-VisionEval#250]
Table 1 in this module documentation does not display properly.
https://github.com/gregorbj/VisionEval/blob/master/sources/modules/VETravelPerformance/inst/module_docs/CalculateVehicleOperatingCost.md#maintenance-repair-and-tire-cost

**Comment by bstabler** [comment]
Moving issues here - https://github.com/VisionEval/VisionEval-Dev/issues
